import { getAdminSeoDashboard } from "@/features/seo/server/admin-insights";

export default async function AdminSeoPage() {
  const data = await getAdminSeoDashboard();
  const cards = [
    ["Published URLs", data.summary.publishedUrls], ["Crawlable URLs", data.summary.crawlableUrls], ["Indexed (sampled)", data.summary.verifiedIndexedUrls], ["Google clicks", data.summary.googleClicks], ["Google impressions", data.summary.googleImpressions], ["Organic signups", data.summary.organicSignups], ["Organic purchases", data.summary.organicPurchases], ["Open alerts", data.summary.openAlerts],
  ];
  return <div className="mx-auto max-w-7xl space-y-8"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-neon">SEO control plane</p><h1 className="mt-2 font-display text-3xl font-extrabold text-brand-white sm:text-4xl">Search performance and publishing health</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">A read-only operating view of the gated SEO system. Publishing, redirects, merges, and pruning remain approval-controlled.</p></header>{data.setupMessage ? <p className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5 text-sm leading-6 text-amber-100">{data.setupMessage}</p> : null}<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <div className="rounded-2xl border border-white/10 bg-brand-panel p-5" key={label as string}><p className="text-sm text-muted">{label}</p><p className="mt-3 font-display text-3xl font-bold text-brand-white">{value as number}</p></div>)}</section><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-brand-panel p-6"><h2 className="font-display text-xl font-bold text-brand-white">Recent alerts</h2>{data.alerts.length ? <ul className="mt-4 space-y-3">{data.alerts.map((alert) => <li className="rounded-xl border border-white/10 p-4" key={alert.id}><p className="text-xs font-bold uppercase text-brand-neon">{alert.severity} · {alert.category}</p><p className="mt-1 font-semibold text-brand-white">{alert.title}</p><p className="mt-1 text-sm text-muted">{alert.message}</p></li>)}</ul> : <p className="mt-4 rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-muted">No SEO alerts recorded.</p>}</div><div className="rounded-2xl border border-white/10 bg-brand-panel p-6"><h2 className="font-display text-xl font-bold text-brand-white">Automation jobs</h2>{data.jobs.length ? <ul className="mt-4 space-y-3">{data.jobs.map((job) => <li className="flex items-center justify-between gap-4 rounded-xl border border-white/10 p-4" key={job.id}><div><p className="font-semibold text-brand-white">{job.loopName}</p><p className="mt-1 text-xs text-muted">Checked {job.checkedCount} · acted {job.actedCount}</p></div><span className="text-xs font-bold uppercase text-brand-neon">{job.status}</span></li>)}</ul> : <p className="mt-4 rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-muted">SEO jobs will appear after the Inngest control plane is enabled.</p>}</div></section></div>;
}
