create table if not exists public.whop_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  whop_membership_id text not null unique,
  whop_plan_id text not null,
  status text not null check (
    status in (
      'trialing',
      'active',
      'past_due',
      'completed',
      'canceled',
      'expired',
      'unresolved',
      'drafted',
      'canceling'
    )
  ),
  last_event_id text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists whop_entitlements_user_id_idx
  on public.whop_entitlements(user_id);

alter table public.whop_entitlements enable row level security;

create policy "Users can read their own Whop entitlements"
  on public.whop_entitlements
  for select
  to authenticated
  using (auth.uid() = user_id);

grant select on public.whop_entitlements to authenticated;

grant select, insert, update on public.whop_entitlements to service_role;

grant usage, select on sequence public.whop_entitlements_id_seq to service_role;
